apiVersion: v1
kind: Secret
metadata:
  name: external-dns-values
stringData:
  values.yml: |
    ---
    deployment:
      args:
      - --registry=txt
      - --txt-owner-id=k8s
      - --txt-prefix=external-dns- 
      - --provider=rfc2136
      - --rfc2136-host=10.0.0.201
      - --rfc2136-port=53
      - --rfc2136-zone=vcf.lab
      - --source=gateway-httproute
      - --domain-filter=apps.vcf.lab
      - --log-level=debug
      - --rfc2136-tsig-axfr
      - --rfc2136-insecure
---
apiVersion: v1
kind: Secret
metadata:
  name: add-gateway-api-overlay
stringData:
  gateway-perms.yml: |
    #@ load("@ytt:overlay", "overlay")

    #@overlay/match by=overlay.subset({"kind":"ClusterRole"}), expects=1
    ---
    rules:
    #@overlay/append
    - apiGroups: ["gateway.networking.k8s.io"]
      resources: ["httproutes","gateways"]
      verbs: ["get", "watch", "list"]
    - apiGroups: [""]
      resources: ["namespaces"]
      verbs: ["get", "watch", "list"]

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: external-dns
  annotations:
    argocd.argoproj.io/sync-wave: '2'
    ext.packaging.carvel.dev/ytt-paths-from-secret-name.0: add-gateway-api-overlay
spec:
  packageRef:
    refName: external-dns.kubernetes.vmware.com
    versionSelection:
      constraints: 0.16.1+vmware.2-vks.1
      prereleases: {}
  serviceAccountName: carvel-sa
  values:
  - secretRef:
      name: external-dns-values
