apiVersion: v1
kind: Secret
metadata:
  name: prometheus-values
stringData:
  values.yml: |
    ---
    #! The namespace in which to deploy prometheus.
    namespace: tanzu-system-monitoring
    prometheus:
      deployment:
        #! Number of prometheus servers
        replicas: 0
        #! Type of prometheus upgrade strategy
      pvc:
        annotations: {}
        storageClassName: null
        accessMode: ReadWriteOnce
        storage: "1Mi"

    ingress:
      enabled: false
      

    alertmanager:
      deployment:
        #! The number of alert manager servers
        replicas: 0
        #! Type of prometheus upgrade strategy
      pvc:
        annotations: {}
        storageClassName: null
        accessMode: ReadWriteOnce
        storage: "1Mi"

    kube_state_metrics:
      deployment:
        replicas: 1
        containers:
          resources: {}
        podAnnotations: {}
        podLabels: {}
      #! kube-state-metrics service configuration
      service:
        type: "ClusterIP"
        port: 80
        targetPort: 8080
        telemetryPort: 81
        telemetryTargetPort: 8081
        labels: {}
        annotations: {}

    node_exporter:
      daemonset:
        hostNetwork: false
        updatestrategy: RollingUpdate
        containers:
          resources: {}
        podAnnotations: {}
        podLabels: {}

      #! node-exporter service configuration
      service:
        type: "ClusterIP"
        port: 9100
        targetPort: 9100
        labels: {}
        annotations: {}


    pushgateway:
      deployment:
        replicas: 0


---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-remove-components
stringData:
  remove.yml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"metadata": {"name": "prometheus-server"}}),expects="1+"
    ---
    #@overlay/remove

    #@overlay/match by=overlay.subset({"metadata": {"name": "prometheus-pushgateway"}}),expects="1+"
    ---
    #@overlay/remove

    #@overlay/match by=overlay.subset({"metadata": {"name": "alertmanager"}}),expects="1+"
    ---
    #@overlay/remove
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    ext.packaging.carvel.dev/ytt-paths-from-secret-name.0: prometheus-remove-components
    argocd.argoproj.io/sync-wave: '1'
  name: prometheus
spec:
  packageRef:
    refName: prometheus.tanzu.vmware.com
    versionSelection:
      constraints: 2.45.0+vmware.1-tkg.3
      prereleases: {}
  serviceAccountName: observability-carvel-sa
  values:
  - secretRef:
      name: prometheus-values