apiVersion: v1
kind: Secret
metadata:
  name: telegraf-values
stringData:
  values.yml: |
    domainName: cluster.local
    isMetricProxyConfigured: true
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: telegraf
spec:
  packageRef:
    refName: telegraf.tanzu.vmware.com
    versionSelection:
      constraints: 1.32.1+vmware.1-tkg.1
      prereleases: {}
  serviceAccountName: observability-carvel-sa
  values:
  - secretRef:
      name: telegraf-values