apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  annotations:
    argocd.argoproj.io/sync-wave: '1'
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'cluster-wide'
        vault.hashicorp.com/agent-inject-secret-db-creds.yaml: 'secret/gitops-6smpt/db-cred2'
        vault.hashicorp.com/tls-skip-verify: 'true'
        vault.hashicorp.com/auth-path: replaceme-with-cluster-name
        vault.hashicorp.com/agent-inject-template-db-config.yaml: |
          {{- with secret "secret/data/my-app/database" -}}
          username: {{ .Data.data.username }}
          password: {{ .Data.data.password }}
          {{- end -}}
    spec:
      containers:
      - image: public.ecr.aws/nginx/nginx
        name: nginx
      serviceAccountName: app-service-account