apiVersion: v1
kind: Namespace
metadata:
    name: sample-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sample-app
  annotations:
    argocd.argoproj.io/sync-wave: '3'
  labels:
    app: httpbin
  name: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
      - image: ghcr.io/mccutchen/go-httpbin
        name: httpbin
        ports:
        - containerPort: 8080
          name: http
      dnsPolicy: ClusterFirst
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: sample-app
  annotations:
    argocd.argoproj.io/sync-wave: '3'
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: httpbin
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin
  annotations:
    argocd.argoproj.io/sync-wave: '3'
    cert-manager.io/cluster-issuer: internal-ca
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: contour
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - secretName: httpbin
    hosts:
    - httpbin.gitops-1.vcf.lab
  rules:
  - host: httpbin.gitops-1.vcf.lab
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: httpbin
            port:
              number: 8080
